# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e765712852ffc0f7b895f000d53386f244ddffabf99b377bae0d0095f21f4a42cb68a386c03a5667048190550ad63eec2d6c9d48b7549653985e60b219e230c

test:
  secret_key_base: 8431f32610df7cacc54e43933bd7c40d279dc5847cd7dce187167316c655e7b094b9da695ac3bee277c894d8869ccd8eed92fc924900d9bf8a0ad74c1774c9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
